apps/books/urls.py
from django.urls import path
from apps.books.views import BookListView, BookDetailView, AuthorListView, AuthorDetailView, GenreListView, \
    GenreDetailView, AddReviewView, AuthorCreateView, AuthorUpdateView, BookCreateView, BookUpdateView

app_name = 'books'
urlpatterns = [
    path('', BookListView.as_view(), name='book_list'),
    path('create', BookCreateView.as_view(), name='book_create'),
    path('authors/', AuthorListView.as_view(), name='author_list'),
    path('genres/', GenreListView.as_view(), name='genre_list'),
    path('authors/create', AuthorCreateView.as_view(), name="author_create"),

    path('<slug:slug>/', BookDetailView.as_view(), name='book_detail'),
    path('<slug:slug>/update/', BookUpdateView.as_view(), name='book_update'),
    path('authors/<int:pk>', AuthorDetailView.as_view(), name='author_detail'),
    path('authors/<int:pk>/update', AuthorUpdateView.as_view(), name='author_update'),
    path('genres/<str:name>/', GenreDetailView.as_view(), name='genre_detail'),
    path('<int:pk>', AddReviewView.as_view(), name="add_review")
]

config/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

from config.settings import STATIC_URL, STATIC_ROOT, MEDIA_URL, MEDIA_ROOT
from config.views import homepage_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage_view, name="homepage"),
    path('accounts/', include("apps.users.urls")),
    path('books/', include("apps.books.urls")),
]
urlpatterns += static(STATIC_URL, document_root=STATIC_ROOT)
urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

apps/books/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models import CASCADE
from django.urls import reverse

from apps.shared.models import AbstractModel


class LanguageChoice(models.TextChoices):
    UZBEK = "UZ", "O'zbekcha"
    ARABIC = "AR", "Arabic"
    ENGLISH = "EN", "English"
    FRENCH = "FR", "French"
    RUSSIAN = "RU", "Russian"


class Book(AbstractModel):
    title = models.CharField(max_length=128)
    slug = models.SlugField(unique=True)
    description = models.TextField()
    published = models.DateField()
    isbn = models.CharField(unique=True, max_length=128)
    language = models.CharField(max_length=14, choices=LanguageChoice.choices)
    page = models.IntegerField()
    cover = models.ImageField(upload_to="books/cover/%Y/%m/%d", default="default/default_user.jpg", blank=True)
    genre = models.ManyToManyField("books.BookGenre", related_name="books")
    authors = models.ManyToManyField("books.Author", related_name="books")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("books:book_detail", kwargs={"slug": self.slug})


class Author(AbstractModel):
    first_name = models.CharField(max_length=56)
    last_name = models.CharField(max_length=56)
    birth_date = models.DateField()
    birth_place = models.CharField(max_length=56)
    website = models.URLField()
    avatar = models.ImageField(upload_to="authors/avatar/%Y/%m/%d")
    about = models.TextField()

    def __str__(self):
        return "{0} {1}".format(self.first_name, self.last_name)

    def get_absolute_url(self):
        return reverse("books:author_detail", kwargs={"pk": self.id})


class BookGenre(AbstractModel):
    name = models.CharField(max_length=28)
    description = models.TextField()

    def __str__(self):
        return self.name


class BookReview(AbstractModel):
    book = models.ForeignKey("books.Book", CASCADE, "reviews")
    user = models.ForeignKey("users.User", CASCADE, "reviews")
    body = models.TextField()
    rating = models.IntegerField(validators=[MaxValueValidator(5), MinValueValidator(1)])
    like_count = models.IntegerField(default=0)

apps/books/forms.py
from django import forms

from apps.books.models import BookReview, Author, Book, BookGenre


class AddBookReviewForm(forms.ModelForm):
    rating = forms.IntegerField(min_value=1, max_value=5)
    body = forms.Textarea(attrs={"rows": "3"})

    class Meta:
        model = BookReview
        fields = ("body", "rating")


class AddAuthorForm(forms.ModelForm):
    avatar = forms.FileField()

    class Meta:
        model = Author
        fields = ("first_name", "last_name", "birth_date", "birth_place", "avatar", "website", "about")


class UpdateAuthorForm(forms.ModelForm):
    avatar = forms.FileField()

    class Meta:
        model = Author
        fields = ("first_name", "last_name", "birth_date", "birth_place", "avatar", "website", "about")


class BookForm(forms.ModelForm):
    cover = forms.FileField()
    authors = forms.ModelMultipleChoiceField(
        queryset=Author.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )
    genre = forms.ModelMultipleChoiceField(
        queryset=BookGenre.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    class Meta:
        model = Book
        fields = ("title", "description", "genre", "authors", "published", "isbn", "language", "page", "cover")

apps/books/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.utils.text import slugify
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from apps.books.forms import AddBookReviewForm, AddAuthorForm, UpdateAuthorForm, BookForm
from apps.books.models import Book, Author, BookGenre, BookReview
from apps.users.models import User


class BookListView(ListView):
    model = Book
    context_object_name = "books"
    template_name = "books/book_list.html"

    def get_queryset(self):
        queryset = super().get_queryset()
        param = self.request.GET.get('q')
        if param:
            quertset = queryset.filter(title__icontains=param)
        return queryset

    # def get_context_data(self, *, object_list=None, **kwargs):
    #     context = super().get_context_data(object_list=object_list, **kwargs)
    #     context["form"] = SearchForm()
    #     return context


class BookDetailView(DetailView):
    model = Book
    # pk_url_kwarg = "slug"
    slug_url_kwarg = "slug"
    context_object_name = "book"
    template_name = "books/book_detail.html"


class AuthorListView(ListView):
    model = Author
    context_object_name = "authors"
    template_name = "books/author_list.html"


class AuthorDetailView(DetailView):
    model = Author
    context_object_name = "author"
    template_name = "books/author_detail.html"


class GenreListView(ListView):
    model = BookGenre
    context_object_name = "genres"
    template_name = "books/genre_list.html"


class GenreDetailView(DetailView):
    model = BookGenre
    slug_field = 'name'
    slug_url_kwarg = 'name'
    context_object_name = "genre"
    template_name = "books/genre_detail.html"


class AddReviewView(View):
    def post(self, request, pk):
        book = Book.objects.get(id=pk)
        user = User.objects.get(username=request.user.username)
        form = AddBookReviewForm(request.POST)
        if form.is_valid():
            BookReview.objects.create(
                user=user,
                book=book,
                body=form.cleaned_data.get("body"),
                rating=form.cleaned_data.get("rating")
            )
            return redirect(reverse("books:book-detail", kwargs={"slug": book.slug}))
        else:
            context = {
                "book": book,
                "form": form
            }
            return render(request, "books/book_detail.html", context=context)


class AuthorCreateView(LoginRequiredMixin, CreateView):
    model = Author
    form_class = AddAuthorForm
    # fields = ("first_name", "last_name", "birth_place", "birth_date", "avatar", "website", "about")
    template_name = "books/author_form.html"
    success_url = reverse_lazy("books:author_list")


class AuthorUpdateView(LoginRequiredMixin, UpdateView):
    model = Author
    form = UpdateAuthorForm
    fields = ("first_name", "last_name", "birth_date", "birth_place", "avatar", "website", "about")
    template_name = "books/author_form.html"


class BookCreateView(LoginRequiredMixin, View):
    def post(self, request):
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            book = Book.objects.create(
                title=form.cleaned_data["title"],
                description=form.cleaned_data["description"],
                cover=form.cleaned_data["cover"],
                published=form.cleaned_data["published"],
                isbn=form.cleaned_data["isbn"],
                language=form.cleaned_data["language"],
                page=form.cleaned_data["page"]
            )
            book.genre.set(form.cleaned_data["genre"])
            book.authors.set(form.cleaned_data["authors"])
            book.slug = slugify(book.title)
            book.save()

            messages.success(request, "Book created")
            return redirect("books:book_list")
        else:
            form = BookForm(request.POST)
            return render(request, "books/book_form.html", {"form": form})

    def get(self, request):
        form = BookForm()
        return render(request, "books/book_form.html", {"form": form})


class BookUpdateView(UpdateView):
    model = Book
    form_class = BookForm
    template_name = "books/book_form.html"

templates/books/author_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{ author.first_name }} {{ author.last_name }}
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-2 offset-md-1">
            <img src="{{ author.avatar.url }}" alt="Author Image" class="img-fluid">
        </div>
        <div class="col-6">
            <h2>{{ author.first_name }} {{ author.last_name }}</h2>
            <span class="d-block"><span class="font-weight-bold">Born: </span>
                {% if author.birth_place %}
                    {{ author.birth_place }}
                {% endif %}/
                {% if author.birth_date %}
                    {{ author.birth_date }}
                {% endif %}
            </span>
            <span class="d-block"><span class="font-weight-bold">Website: </span>
                <a href="{{ author.website }}">{{ author.website }}</a>
            </span>
            <span class="d-block my-2">{{ author.about }}</span>
            {% if user.is_staff %}
                <a href="{% url 'books:author_update' author.id %}" class="btn btn-primary">Edit</a>
            {% endif %}
        </div>
    </div>
    <hr>
    <h2 class="text-center">Author Books</h2>
    <div class="row mt-3">
        {% for book in author.books.all %}
            <div class="col-2">
                <div class="card">
                    <img src="{{ book.cover.url }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h6><a href="{% url 'books:book_detail' book.slug %}">{{ book.title }}</a></h6>
                        <span class="text-muted">Rating info will be included</span>
                    </div>
                </div>
            </div>
        {% endfor %}

    </div>
{% endblock %}

templates/books/author_form.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
    Add New Author
{% endblock %}
{% block content %}
    <div class="row pb-5">
        <div class="col-8 offset-md-2">
            <h2>Add new auhor</h2>
            <form enctype="multipart/form-data" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" class="btn btn-outline-dark w-100" value="Save">
            </form>
        </div>
    </div>
{% endblock %}

templates/books/author_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Author List
{% endblock %}
{% block content %}
    <h2 class="text-danger">Authors</h2><br>
    {% for author in authors %}

        <div class="row border rounded p-1 m-2">
            <div class="col-2">
                <img src="{{ author.avatar.url }}" alt="No img..." class="img-fluid">
            </div>
            <div class="col-6 py-5">
                <a href="{% url 'books:author_detail' author.id %}">
                    <h2>{{ author.first_name }} {{ author.last_name }}</h2></a>
                <a href="{{ author.website }}">{{ author.website }}</a>
            </div>
        </div>
    {% endfor %}
        <a href="{% url 'books:author_create' %}" class="btn btn-outline-primary">Add new author</a>


{% endblock %}

templates/books/book_detail.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
    {{ book.title }}
{% endblock %}
{% block content %}
    <div class="mt-4 row">
        <div class="col-3 justify-content-center">
            <img src="{{ book.cover.url }}" alt="No imag..." class="img-thumbnail">
        </div>
        <div class="col-6">
            <h2>{{ book.title }}</h2>
            <div>
                <span class="h4">Authors: </span>
                {% for author in book.authors.all %}
                    <a href="{% url 'books:author_detail' author.id %}"
                       class="h4">{{ author.first_name }} {{ author.last_name }}</a>
                {% endfor %}
            </div>
            <div>
                <span class="h4">Genres: </span>
                {% for genre in book.genre.all %}
                    <a href="" class="h4">{{ genre.name }}</a>
                {% endfor %}
            </div>
            <p class="my-3 font-italic">{{ book.description }}</p>
            {% if user.is_staff %}
                <a href="{% url 'books:book_update' book.slug %}" class="btn btn-primary">Edit</a>
            {% endif %} 
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-8 offset-md-2">
            <div class="justify-content-around">
                <h4>Reviews</h4>
                <div>
                    <p>
                        <a class="" data-toggle="collapse" href="#collapseExample" role="button"
                           aria-expanded="false" aria-controls="collapseExample">
                            Add Review
                        </a>

                    </p>
                    <div class="collapse" id="collapseExample">
                            <form method="post" action="{% url 'books:add_review' book.pk %}" class="border p-2">
                                {% csrf_token %}
                                {{ form|crispy }}
                                <input type="submit" value="Save">
                            </form>
                    </div>
                </div>
            </div>

            {% for review in book.reviews.all %}
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ review.user.username }}</h5>
                        <p class="card-text">{{ review.body }}</p>
                        <span class="text-muted">Rated {{ review.rating }} out of 5</span>
                    </div>
                </div>
            {% endfor %}

        </div>
    </div>
{% endblock %}

templates/books/book_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Add new book
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-8 offset-md-2">
            <h2>Add new Book</h2>
            <form enctype="multipart/form-data" method="post" class="my-2">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" value="Save" class="btn btn-outline-dark">
            </form>
        </div>
    </div>
{% endblock %}

templates/books/book_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Book list
{% endblock %}
{% block content %}
    <h2 class="my-3 text-danger">Books</h2>
    {% for book in books %}
        <div class="row py-3">
            <div class="col-3">
                <img src="{{ book.cover.url }}" alt="No img..." class="img-fluid">
            </div>
            <div class="col-6">
                <a href="{% url 'books:book_detail' book.slug %}">
                    <h3>{{ book.title }}</h3>
                </a>
                <a href="#">
                    <h5>{{ book.author }}</h5>
                </a>
                <p>{{ book.description }}</p>
            </div>
        </div>
        <hr>
    {% empty %}
        <div class="alert alert-secondary text-center">
        <h5>No books</h5>
            <a href="{% url 'homepage' %}">Back to homepage</a>
        </div>
    {% endfor %}

        <a href="{% url 'books:book_create' %}" class="btn btn-outline-primary">Add new book</a>

{% endblock %}

templates/books/genre_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{ genre.name }}
{% endblock %}
{% block content %}
    <div class="row mt-3 mb-5">
        <div class="col-8 offset-md-1">
            <h3>{{ genre.name }}</h3>
            {{ genre.description }}
        </div>
    </div>
    <hr>
    <h4>Books in {{ genre.name }}</h4>
    <div class="row">
        {% for book in genre.books.all %}
            <div class="col-3">
                <div class="card">
                    <img class="card-img-top img-thumbnail" src="{{ book.cover.url }}" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title"><a href="{% url 'books:book_detail' book.slug %}">{{ book.title }}</a></h5>
                        <a href="{% url 'books:book_detail' book.slug %}" class="btn btn-primary">Book details</a>
                    </div>
                </div>
            </div>
        {% endfor %}


    </div>
{% endblock %}

templates/books/genre_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Genres
{% endblock %}
{% block content %}
    <h2 class="mt-3 mb-2 text-danger">Genres</h2><br>
    <div class="row p-2 m-2">
        {% for genre in genres %}
            <div class="col-8 my-2">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">{{ genre.name }}</h4>
                        <p class="card-text">{{ genre.description|slice:64 }}...</p>
                        <a href="{% url 'books:genre_detail' genre.name %}" class="card-link">More about {{ genre.name }}</a>
                    </div>
                </div>
                <br>
            </div>
        {% endfor %}

    </div>
{% endblock %}

templates/books/review_form.html
<form method="post" class="border p-2">
    {{ form|crispy }}
    <input type="submit" value="Save">
</form>