apps/books/urls.py
from django.urls import path
from apps.books.views import BookListView, BookDetailView, AuthorListView, AuthorDetailView, GenreListView, \
    GenreDetailView, AddReviewView, AuthorCreateView, AuthorUpdateView, BookCreateView, BookUpdateView

app_name = 'books'
urlpatterns = [
    path('', BookListView.as_view(), name='book_list'),
    path('create', BookCreateView.as_view(), name='book_create'),
    path('authors/', AuthorListView.as_view(), name='author_list'),
    path('genres/', GenreListView.as_view(), name='genre_list'),
    path('authors/create', AuthorCreateView.as_view(), name="author_create"),

    path('<slug:slug>/', BookDetailView.as_view(), name='book_detail'),
    path('<slug:slug>/update/', BookUpdateView.as_view(), name='book_update'),
    path('authors/<int:pk>', AuthorDetailView.as_view(), name='author_detail'),
    path('authors/<int:pk>/update', AuthorUpdateView.as_view(), name='author_update'),
    path('genres/<str:name>/', GenreDetailView.as_view(), name='genre_detail'),
    path('<int:pk>', AddReviewView.as_view(), name="add_review")
]

apps/users/urls.py
from django.urls import path
from apps.users.views import LoginView, RegisterView, LogoutView, ProfileView

app_name = "users"
urlpatterns = [
    path('register', RegisterView.as_view(), name="register"),
    path('login', LoginView.as_view(), name="login"),
    path('logout', LogoutView.as_view(), name="logout"),

    path('profile/<str:username>', ProfileView.as_view(), name="profile"),
]

config/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

from config.settings import STATIC_URL, STATIC_ROOT, MEDIA_URL, MEDIA_ROOT
from config.views import homepage_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage_view, name="homepage"),
    path('accounts/', include("apps.users.urls")),
    path('books/', include("apps.books.urls")),
]
urlpatterns += static(STATIC_URL, document_root=STATIC_ROOT)
urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>{% block title %}Goodreads{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>

<body>
<nav class="p-3 navbar navbar-expand-lg navbar-dark bg-success">
    <div class="container justify-content-between">
        <a class="navbar-brand" href="{% url 'homepage' %}">
{#            <img src="{% static 'img/logo.png' %}" class="d-inline-block align-top" alt=""/>#}
            <h1>Goodreads</h1>
        </a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a href="{% url 'homepage' %}" class="nav-link text-light">Home</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'books:book_list' %}" class="nav-link text-light">Books</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'books:genre_list' %}" class="nav-link text-light">Genres</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'books:author_list' %}" class="nav-link text-light">Authors</a>
            </li>
        </ul>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            {% if user.is_authenticated %}
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <div class="dropdown show">
                            <a class="nav-link dropdown-toggle custom" href="#" role="button" id="dropdownMenuLink"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{ user.username|title }}
                            </a>

                            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                <a class="dropdown-item" href="{% url 'users:profile' user.username %}">Profile</a>
                                <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
                            </div>
                        </div>
                    </li>
                </ul>
            {% else %}
                <form class="form-inline ml-auto">
                    <a href="{% url 'users:login' %}" class="btn btn-outline-light">Login</a>
                    <a href="{% url 'users:register' %}" class="btn btn-light ml-2">Register</a>
                </form>
            {% endif %}
        </div>
    </div>
</nav>
<br>


<div class="container p-3">
    {% include 'messages.html' %}

    {% block content %}
    {% endblock content %}
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

</body>

</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Homepage
{% endblock %}
{% block content %}
    <div class="row">
        <h1 class="text-danger">BOOKS</h1>
    <p>ook is a medium for recording information in the form of writing or images. Books are typically composed of many pages, bound together and protected by a cover.[1] Modern bound books were preceded by many other written mediums, such as the codex and the scroll. The book publishing process is the series of steps involved in their creation and dissemination.</p>
    </div>
{% endblock %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            <h6>{{ message|safe }}</h6>
        </div>
    {% endfor %}
{% endif %}